# Generated by Django 5.0.4 on 2024-04-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("date_pub", models.DateTimeField(auto_now_add=True)),
                ("date_mod", models.DateTimeField(auto_now=True)),
                ("units", models.SmallIntegerField()),
                ("lec_hours", models.SmallIntegerField()),
                ("lab_hours", models.SmallIntegerField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prelim",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "midterm",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "prefinal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "final",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="teachers.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject",
                        to="teachers.subject",
                    ),
                ),
            ],
        ),
    ]
