# Generated by Django 5.0.4 on 2024-04-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0002_academicyear_advertisement_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_year",
                to="staffs.academicyear",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                choices=[
                    ("1ST", "First Semester"),
                    ("2ND", "Second Semester"),
                    ("3RD", "Third Semester"),
                    ("SUM", "Summer"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
