# Generated by Django 5.0.4 on 2024-04-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0003_alter_semester_academic_year_alter_semester_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_year",
                to="staffs.academicyear",
            ),
        ),
    ]
