# Generated by Django 5.0.4 on 2024-04-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0004_alter_semester_academic_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("semester", "academic_year")},
        ),
    ]
