# Generated by Django 5.0.4 on 2024-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0005_alter_semester_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="date_upd",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="date_mod",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
