# Generated by Django 5.0.4 on 2024-04-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0006_remove_advertisement_date_upd_advertisement_date_mod"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("date_pub", models.DateTimeField(auto_now_add=True)),
                ("date_mod", models.DateTimeField(auto_now=True)),
                ("units", models.SmallIntegerField()),
                ("lec_hours", models.SmallIntegerField()),
                ("lab_hours", models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="subjects",
            field=models.ManyToManyField(related_name="subjects", to="staffs.subject"),
        ),
    ]
