# Generated by Django 4.2 on 2024-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0007_subject_customuser_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="content",
            field=models.TextField(default="Hello"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("start_year", "end_year")},
        ),
    ]
