# Generated by Django 4.2 on 2024-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0008_advertisement_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="utype",
            field=models.CharField(
                choices=[
                    ("STU", "Student"),
                    ("TEA", "Teacher"),
                    ("CAS", "Cashier"),
                    ("STA", "Staff"),
                ],
                max_length=20,
            ),
        ),
    ]
